### ISSUE TITLE
TODO : Contract1

### ISSUE THREAD

**Issue by Vinlagrenouille** [Perciii/J-Voting#2]
Une classe immuable Alternative qui contient simplement un id (entier). Une classe immuable StrictPreference qui contient une liste d’alternatives (représentant un rangement par ordre de préférence des alternatives, strict signifiant sans ex-æquo), qui ne contient pas deux fois la même alternative. Une classe immuable Voter qui contient un id (entier).

CF : https://github.com/oliviercailloux/projets/blob/master/SE/J-Voting.adoc

**Comment by oliviercailloux** [comment]
Veuillez créer une issue dont le nom est exactement Contract1 (même chose pour l’autre)

**Comment by Vinlagrenouille** [comment]
C'est noté pour nous. Nous en tiendrons compte pour la prochaine deadline.

Cordialement,

Vincent Navales

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________
